# Digit Recognition Notebook (unfinished)
### James Kinsella - G00282261@gmit.ie

In [2]:
# import keras packages
# NOTE: To import the keras package you must install tensorflow - which can be found here: https://www.tensorflow.org/install/
import keras as kr

# Create the sequential model
model = kr.models.Sequential()

# Add layers to the model
model.add(kr.layers.Dense(units=1000, activation='linear', input_dim=784))
model.add(kr.layers.Dense(units=400, activation='relu'))
model.add(kr.layers.Dense(units=10, activation='softmax'))

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

C:\Users\Cheech\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [5]:
# Import the gzip and numpy packages
import gzip
import numpy as np

# This opens the images file which is located in our local directory and assigns the read in value to a variable
with gzip.open('C:/Users/Cheech/source/repos/EmergingTechnologies/data/t10k-images-idx3-ubyte.gz', 'rb') as f:
    image_content = f.read()
    
# This opens the label file which is located in our local directory and assigns the read in value to a variable
with gzip.open('C:/Users/Cheech/source/repos/EmergingTechnologies/data/t10k-labels-idx1-ubyte.gz', 'rb') as f:
    label_content = f.read()
    
# This opens the training images file which is located in our local directory and assigns the read in value to a variable
with gzip.open('C:/Users/Cheech/source/repos/EmergingTechnologies/data/train-images-idx3-ubyte.gz', 'rb') as f:
    train_img = f.read()

# This opens the training label file which is located in our local directory and assigns the read in value to a variable
with gzip.open('C:/Users/Cheech/source/repos/EmergingTechnologies/data/train-labels-idx1-ubyte.gz', 'rb') as f:
    train_lbl = f.read()
    
# Assign the training data set to a numpy array holding all the values in a 28x28 array
train_img = ~np.array(list(train_img[16:])).reshape(60000, 28, 28).astype(np.uint8) / 255.0
# Assign the training label data set to a numpy array
train_lbl =  np.array(list(train_lbl[8:])).astype(np.uint8)

In [6]:
# Assign the data set to a numpy array holding all the values in a 28x28 array
image_test = ~np.array(list(image_content[16:])).reshape(10000,28,28).astype(np.uint8)

# Assign the label data set to a numpy array
label_test =  np.array(list(label_content[8:])).astype(np.uint8)

# Display the bytes as 1s and 0s in an array
print((~image_test[0]).astype(np.bool).astype(np.uint8))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 

In [7]:
# Reshape the 3D array into a 1D array
inputs = train_img.reshape(60000, 784)
# Print the 1D array of inputs
print(inputs)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [8]:
# For encoding categorical variables.
import sklearn.preprocessing as pre

# set up the binary encoder
encoder = pre.LabelBinarizer()
# fit the labels into the binary format
encoder.fit(train_lbl)
# Transform the labels to the binary format
outputs = encoder.transform(train_lbl)

# Print the labels position and the binary array in the same position
# Result should show the label number 5 and a 1 in the 6th position to indicate the number 5 (0-9)
print(train_lbl[19], outputs[19])

9 [0 0 0 0 0 0 0 0 0 1]


In [9]:
for i in range(10):
    print(i, encoder.transform([i]))

0 [[1 0 0 0 0 0 0 0 0 0]]
1 [[0 1 0 0 0 0 0 0 0 0]]
2 [[0 0 1 0 0 0 0 0 0 0]]
3 [[0 0 0 1 0 0 0 0 0 0]]
4 [[0 0 0 0 1 0 0 0 0 0]]
5 [[0 0 0 0 0 1 0 0 0 0]]
6 [[0 0 0 0 0 0 1 0 0 0]]
7 [[0 0 0 0 0 0 0 1 0 0]]
8 [[0 0 0 0 0 0 0 0 1 0]]
9 [[0 0 0 0 0 0 0 0 0 1]]


In [10]:
model.fit(inputs, outputs, epochs=2, batch_size=100)

Epoch 1/2
60000/60000 [==============================] - 35s 586us/step - loss: 0.7471 - acc: 0.7873
Epoch 2/2
60000/60000 [==============================] - 33s 554us/step - loss: 0.3953 - acc: 0.8855


In [ ]:
# Import the matplotlib package
import matplotlib.pyplot as plt

# Train the model and assign it to a variable so we can use it to plot our data
training = model.fit(inputs, outputs, epochs=20, validation_split=0.25, batch_size=100, verbose=1)

#NOTE: If graph doesnt show after first run, rerun the initial model set up at the top and rerun this block again

# Plot training & validation accuracy values
plt.plot(training.history['acc'])
plt.plot(training.history['val_acc'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='lower right')
plt.show()

# Plot training & validation loss values
plt.plot(training.history['loss'])
plt.plot(training.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

Train on 45000 samples, validate on 15000 samples
Epoch 1/20
45000/45000 [==============================] - 29s 637us/step - loss: 0.3531 - acc: 0.8966 - val_loss: 0.3330 - val_acc: 0.9017
Epoch 2/20
45000/45000 [==============================] - 24s 542us/step - loss: 0.3275 - acc: 0.9031 - val_loss: 0.3016 - val_acc: 0.9111
Epoch 3/20
45000/45000 [==============================] - 26s 571us/step - loss: 0.3104 - acc: 0.9093 - val_loss: 0.2996 - val_acc: 0.9085
Epoch 4/20
45000/45000 [==============================] - 25s 548us/step - loss: 0.2929 - acc: 0.9136 - val_loss: 0.2805 - val_acc: 0.9172
Epoch 5/20
45000/45000 [==============================] - 25s 564us/step - loss: 0.2798 - acc: 0.9182 - val_loss: 0.2695 - val_acc: 0.9209
Epoch 6/20
45000/45000 [==============================] - 26s 567us/step - loss: 0.2673 - acc: 0.9218 - val_loss: 0.2599 - val_acc: 0.9257
Epoch 7/20
45000/45000 [==============================] - 27s 592us/step - loss: 0.2557 - acc: 0.9257 - val_loss: 0.